name: Auto-release

on:
  # ATM, this is the closest trigger to a PR merging
  workflow_run:
    workflows: [Python Tests]
    branches: [main]
    types: [completed]

env:
  AUTO_VERSION: v11.1.2

jobs:
  auto-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare repository
        # Fetch full git history and tags
      run: git fetch --unshallow --tags

    - name: Unset header
        # checkout@v2 adds a header that makes branch protection report errors
        # because the Github action bot is not a collaborator on the repo
      run: git config --local --unset http.https://github.com/.extraheader

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download auto
      env:
        AUTO_VERSION: v11.1.2
      run: |
        # Direct URL: /download/<tag>/<asset-name>
        wget -qO- \
          "https://github.com/intuit/auto/releases/download/${AUTO_VERSION}/auto-linux.gz" \
          | gunzip > ~/auto
        chmod +x ~/auto

    - name: Create release
      run: |
        ~/auto shipit -vv
      env:
        GH_TOKEN: ${{ secrets.AUTO_ORG_TOKEN }}
